# 应用名称
spring.application.name=Nuist_CampusWall

# 数据源
spring.datasource.url=jdbc:mysql://localhost:3306/campuswall?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true

# 数据源连接信息
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080

# 数据库初始化
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/db_init.sql
spring.sql.init.data-locations=classpath:sql/db_seed.sql
spring.sql.init.continue-on-error=false

# mybatis-plus配置
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# jwt 配置
jwt.secret=Nuist_CampusWall_Application@key_wsq
jwt.expire-seconds=7200
jwt.issuer=nuist-campuswall

# 管理员用户id
app.admin-user-id=1

# 上传文件最大大小（5MB）
app.file.max-image-size=5242880
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 本地文件上传路径
app.file.local-root=D:/campuswall_upload

# 文件访问路径前缀
app.file.url-prefix=/static/upload

# 临时文件清理任务cron（测试时可改成每分钟）
app.file.clean-temp-cron=0 0 * * * ?


